### PR TITLE
[IT-3758] Give 4 points access to usage reports

### PR DESCRIPTION
**Pull request by zaro0508**
Four points needs access to AWS usage reports to generate cost summery level reports.

from  four points...
```
Good morning.  I have accessed the account to complete our first month of billing. 
I just realized we don’t have access to the usage report that we need.
I will only be able to provide summary level reporting this month. 
Can we get the detail billing report and a CUR report setup for our use?  
I can provide details on what we need if needed.
```

* Give four points access to view usage from aws portal
* Give four points full access to bucket folder "cost-and-usage-reports.sagebase.org/4points" to allow sending their reports to that folder.  Setup this policy from  bcm-data-exports-access-examples[1] and example-bucket-policies-folders[2] docs.

[1] https://docs.aws.amazon.com/cur/latest/userguide/bcm-data-exports-access.html#bcm-data-exports-access-examples
[2]  https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-bucket-policies.html#example-bucket-policies-folders

### CODE REVIEW

**Comment by jesusaurus** [comment]
I'm not quite sure what Four Points is asking for. We already have a CUR configured to export into the bucket `cost-and-usage-reports.sagebase.org`, and they should already be able to access that bucket.

**Review by brucehoff — COMMENTED** [review]
@zaro0508 The policy you added, `AWSAccountUsageReportAccess` provides the `aws-portal:ViewUsage` action.  Have you confirmed with Four Points that this is the additional access they are asking for when they say, "detail billing report and a CUR report "?  For example the CUR report is a set of parquet files in an S3 bucket. Does Four Point need access to that bucket?

**Comment by zaro0508** [comment]
@jesusaurus 
> I'm not quite sure what Four Points is asking for.

i'm guessing that they want to view usage from the AWS console.


@brucehoff 

> Have you confirmed with Four Points that this is the additional access they are asking for when they say, "detail billing report and a CUR report "? 

No, i have not.

> Does Four Point need access to that bucket?

I have no idea.

**Comment by zaro0508** [comment]
Can you please take another look @jesusaurus and @brucehoff ?

**Review by jesusaurus — APPROVED** [review]

**Comment by brucehoff** [comment]
> @jesusaurus
> 
> > I'm not quite sure what Four Points is asking for.
> 
> i'm guessing that they want to view usage from the AWS console.
> 
> @brucehoff
> 
> > Have you confirmed with Four Points that this is the additional access they are asking for when they say, "detail billing report and a CUR report "?
> 
> No, i have not.
> 
> > Does Four Point need access to that bucket?
> 
> I have no idea.

@zaro0508 Here's some follow on correspondence to help you decide if the proposed permissions are correct.  They sent this after I asked them to create their own CUR using their current permissions:

```
Good morning. As expected, I don’t have the needed permissions to setup a CUR report. AWS’ new granular permissioning is not making this easy. :) It might be easier to just provide access to data exports and CUR broadly at least temporarily.  I believe I can setup the legacy detailed billing reports (which are our preference) but cannot create an S3 bucket in either case.  So would need you to either give me appropriate S3 permissions or create a bucket for me.  Below is the additional permissions I think I need (excluding the change to S3):

{

              "Version": "2012-10-17",

              "Statement": [

                             {

                                           "Sid": "VisualEditor0",

                                           "Effect": "Allow",

                                           "Action": [

                                                          "bcm-data-exports:*",

                                                          "cur:*",

                                           ],

                                           "Resource": "*"

                             }

              ]

}

 

Let me know if you have any thoughts and concerns.  I am trying to complete July’s invoicing, but I don’t know have access to the details needed to apply CloudFront and S3 special pricing. 
```

**Comment by zaro0508** [comment]
@brucehoff yes, i saw the email.  I have already incorporated 4point's request into this PR.  can you please take another look?

**Review by brucehoff — APPROVED** [review]
Please check with Michelle that she can now create the report(s) she needs.

**Pull request merged**
