### PR TITLE
[IT-3891] Create AWS account for openchallenges dev

### PR DESCRIPTION
**Pull request by zaro0508**
Create an AWS account for openchallenges development environment.

### CODE REVIEW

**Review by xschildw — APPROVED** [review]
No cost center?

**Review by tschaffter — COMMENTED** [review]
The cost center is ITCR / 10160004.

**Comment by zaro0508** [comment]
> No cost center?

nice catch, do you have a cost center for us to apply to this account @tschaffter?

**Review by xschildw — APPROVED** [review]

**Comment by tschaffter** [comment]
> [number should match finance code](https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/1213/commits/31888014d0b8503288bcfff1f8d4ea2e5fce9db6)

Where can I find the reference finance code? I remember that Joni created a microservice/lambda function for that.

The code I shared comes from a template we have in Jira. I'll double check to know which one is correct.

**Review by tschaffter — APPROVED** [review]

**Comment by zaro0508** [comment]
> > [number should match finance code](https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/1213/commits/31888014d0b8503288bcfff1f8d4ea2e5fce9db6)
> 
> @zaro0508 Where can I find the reference finance code? I remember that Joni created a microservice/lambda function for that.
> 
> The code I shared comes from a template we have in Jira. I'll double check to know which one is correct.

@tschaffter here are the codes https://sagebionetworks.jira.com/wiki/spaces/IT/pages/2553544733/Finance+Program+Codes

**Pull request merged**
