### PR TITLE
[ETL-275] Set up JumpCloud access for RECOVER dev account

### PR DESCRIPTION
**Pull request by rxu17**
This PR builds on top of now merged [#649](https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/649) and the goal is to set up access to the AWS account via JumpCloud. 
Ideally, admin, developer and viewer roles are created.

A blank placeholder document (for the purpose of creating the initial PR and will be deleted later prior to merging) has been generated at _/.../org-formation/600-access/etl_275_blank_file.txt

PR Checklist:
[X] Describe and explain your intentions for this change
[X] Setup pre-commit and run the validators (info in README.md)

### CODE REVIEW

**Comment by zaro0508** [comment]
i'm not sure what this PR is about.  If you want to setup access via jumpcloud then you'll need to add something similar to this.. https://github.com/Sage-Bionetworks-IT/organizations-infra/blob/master/org-formation/700-aws-sso/_tasks.yaml#L1245-L1294

**Comment by thomasyu888** [comment]
@rxu17 could you mimic something like this: https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/136/files and add in the sections similar to what Khai linked above?

@zaro0508 , in that same PR, there was an XML file you provided.  Will you be providing this file or do we not need to worry about that anymore.

**Comment by zaro0508** [comment]
xml file was the old approach, we don't need that anymore.  You will just need to add something similar to https://github.com/Sage-Bionetworks-IT/organizations-infra/blob/master/org-formation/700-aws-sso/_tasks.yaml#L1245-L1294

**Comment by thomasyu888** [comment]
@rxu17 I stand corrected - please follow @zaro0508's instructions. Thanks Khai!

**Comment by rxu17** [comment]
Done

**Comment by thomasyu888** [comment]
@rxu17 can you remove the empty file?

**Review by brucehoff — COMMENTED** [review]
Two questions:
(1) It looks like this PR was initially rejected for using an 'old approach'.  Where are the instructions you followed?  Do they need to be updated to give the right guidance?
(2) The "recover-dev" account already had admin, viewer and viewer-plus roles.  What is reason or the affect of this PR?

**Comment by thomasyu888** [comment]
I updated the instructions. But how does the recover dev account have admin/viewer/viewer plus roles? Were these added already?

**Comment by jesusaurus** [comment]
@thomasyu888 yeah, those roles are created automatically for every member account (e.g. [here](https://github.com/Sage-Bionetworks-IT/organizations-infra/blob/master/org-formation/700-aws-sso/_tasks.yaml#L332) for the viewer role)

**Comment by thomasyu888** [comment]
Oh! That's nice! I didn't realize those jumpcloud roles were automatically created.  If that's the case, we can probably close these tickets? I'll open a IT ticket to add all of us to those roles so we can gain access to the accounts.

**Comment by brucehoff** [comment]
Although the roles are created automatically, it seems that this PR is needed to link things up.  (See steps 9 and 10 of [these](https://sagebionetworks.jira.com/wiki/spaces/IT/pages/745373697/Setup+AWS+Accounts) instructions. )

**Review by brucehoff — CHANGES_REQUESTED** [review]
@rxu17 This PR needs to look more like #654 , specifically it needs the groups IDs (which we just created in the Organizations account):
recoverDevAdminGroup 94a8e488-00d1-70a4-1c05-d864077490d6
recoverDevDeveloperGroup 54e8e448-1051-70e2-2607-b109750355bd
recoverDevViewerGroup a46824e8-e0d1-709b-457d-90d57d6a71be

Will you please update this PR and resubmit?

**Review by brucehoff — APPROVED** [review]

**Review by zaro0508 — APPROVED** [review]

**Comment by brucehoff** [comment]
@rxu17 There are conflicts in this pull request.  Can you please resolve and update the PR?

**Comment by rxu17** [comment]
> @rxu17 There are conflicts in this pull request. Can you please resolve and update the PR?

Done!

**Review by brucehoff — APPROVED** [review]

**Pull request merged**
