### PR TITLE
[IT-1766] Restore AWS region restriction

### PR DESCRIPTION
**Pull request by zaro0508**
Restrict accounts from creating resources in regions outside of the US
region.

### CODE REVIEW

**Comment by zaro0508** [comment]
Region restriction was disabled due to issue IT-1766, we need to make sure it can work before merging this PR.

**Review by brucehoff — APPROVED** [review]
This seems OK as long as it omits Synapse which does, in places, require the use of resources outside the US.

**Review by xschildw — APPROVED** [review]
So you're putting it back so AWS can investigate?

**Comment by zaro0508** [comment]
this has been replaced with PR #624

**Pull request closed without merging**
