### PR TITLE
IT-1909: Add NLPSandbox VPC to TGW

### PR DESCRIPTION
**Pull request by xschildw**
This PR adds the NLPSandbox VPC to TGW and gives access to mebers of the aws-nlpsandbox-admins JC groiup.

### CODE REVIEW

**Review by thomasyu888 — APPROVED** [review]

**Comment by xschildw** [comment]
Good point! I was just re-implementing the existing setup. @thomasyu888 / @tschaffter , would session manager meet your needs to connect to instances or do you actually need VPN access?

**Comment by thomasyu888** [comment]
@zaro0508 Just wanted to validate the approach to modifying the stack in NLPSandbox infra to use ssm manager in my comment above.

**Review by zaro0508 — CHANGES_REQUESTED** [review]
probably just close this?

**Comment by xschildw** [comment]
This account is not needed anymore.

**Pull request closed without merging**
