### PR TITLE
[IT-1234] Use updated templates for VPN access

### PR DESCRIPTION
**Pull request by zaro0508**
Use new version of SC templates that provide transit gateway
access to instances which allows access from the VPN

depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/275

### CODE REVIEW

**Comment by zaro0508** [comment]
hold off on merging until @brucehoff fixes issues with the notebook product in packer-rstudio repo.

**Comment by zaro0508** [comment]
hold off on merging until @brucehoff fixes issues with the notebook product in packer-rstudio repo.

**Comment by zaro0508** [comment]
hold off on merging until @brucehoff fixes issues with the notebook product in packer-rstudio repo.

**Comment by brucehoff** [comment]
> hold off on merging until @brucehoff fixes issues with the notebook product in packer-rstudio repo.

Can you explain how this work depends on updating the `packer-rstudio` repo'?  They seem totally unrelated to me.

**Comment by zaro0508** [comment]
@brucehoff This PR updates the version of `sc-product-ec2-linux-jumpcloud-notebook.yaml` however the current notebook is broken due to [updating the AMI in your change](https://github.com/Sage-Bionetworks/service-catalog-library/compare/v1.1.33...v1.1.34).  This PR requires crating a new tag of service-catalog-library and I don't want to create a tag of master when it's in a broken state.

**Comment by zaro0508** [comment]
this PR is replaced by PR #473

**Pull request closed without merging**
